#include <lexkit/types.h>

typedef enum 
{
  BRK_DI = 0, // Direct break opportunity
  BRK_IN = 1, // Indirect break opportunity
  BRK_CI = 2, // Indirect break opportunity for combining marks
  BRK_CP = 3, // Prohibited break for combining marks
  BRK_PR = 4, // Prohibited break
} BRK;

// Based on example pair table from https://www.unicode.org/reports/tr14/tr14-37.html#Table2
// - ZWJ special processing for LB8a of Revision 41
// - CB manually added as per Rule LB20
// - CL, CP, NS, SY, IS, PR, PO, HY, BA, B2 and RI manually adjusted as per LB22 of Revision 45
const BRK g_pair_table[33][33] = {
  //OP   , CL    , CP    , QU    , GL    , NS    , EX    , SY    , IS    , PR    , PO    , NU    , AL    , HL    , ID    , IN    , HY    , BA    , BB    , B2    , ZW    , CM    , WJ    , H2    , H3    , JL    , JV    , JT    , RI    , EB    , EM    , ZWJ   , CB
  {BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_CP, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_PR}, // OP
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // CL
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // CP
  {BRK_PR, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_CI, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN}, // QU
  {BRK_IN, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_CI, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN}, // GL
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // NS
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // EX
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_DI, BRK_IN, BRK_DI, BRK_IN, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // SY
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // IS
  {BRK_IN, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI}, // PR
  {BRK_IN, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // PO
  {BRK_IN, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // NU
  {BRK_IN, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // AL
  {BRK_IN, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // HL
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_IN, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // ID
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // IN
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_DI, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_DI, BRK_IN, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // HY
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_DI, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // BA
  {BRK_IN, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_CI, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_DI}, // BB
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_PR, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // B2
  {BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI}, // ZW
  {BRK_IN, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // CM
  {BRK_IN, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_CI, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN}, // WJ
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_IN, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // H2
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_IN, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // H3
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_IN, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // JL
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_IN, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // JV
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_IN, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // JT
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // RI
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_IN, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_DI}, // EB
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_IN, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // EM
  {BRK_IN, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_PR, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_IN, BRK_IN, BRK_IN, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}, // ZWJ
  {BRK_DI, BRK_PR, BRK_PR, BRK_IN, BRK_IN, BRK_DI, BRK_PR, BRK_PR, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_PR, BRK_CI, BRK_PR, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_DI, BRK_IN, BRK_DI}  // CB
};
